 version: '3'
    
 services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
        - /var/lib/postgresql/12:/var/lib/postgresql/data
    web:
      build: .
      ports:
      - "8080:80"
      - "8000:8000"
      volumes:
      - /var/www/html:/var/www/html
      depends_on:
        - db
